"""Standalone colon-only NCC anchor for HUD value rows.

The SC mining HUD's three value rows (MASS, RESISTANCE, INSTABILITY)
each end with a colon (":") immediately before the value. The primary
anchor — full-label NCC against MASS / RESISTANCE / INSTABILITY
templates (``ocr/sc_ocr/label_match.py``) — fails when the label text
is occluded, dim, or chromatically aberrated enough to drop the per-
template NCC below threshold. In those cases ``_label_rows_from_anchor``
falls back to whichever row DID match, producing oversized value crops
that the CRNN reads as spurious "0" digits.

This module provides a SECOND, INDEPENDENT anchor: the colon glyph
itself. Colons are tiny (~3-6 px × ~10-14 px), two-stacked-dot
patterns that are visually identical across all three labels and at
all HUD scales. NCC against a canonical colon template recovers row
positions even when the label words don't match.

Mirrors the architectural pattern of the signature pipeline, which
combines a primary icon-NCC anchor with a content-based digit-cluster
anchor for redundancy.

Public API::

    from ocr.sc_ocr.colon_anchor import find_colons

    colons = find_colons(
        img,
        y_band=(top_y, bot_y),
        x_range=(label_left_x, value_right_x),
    )
    # colons = [
    #     {"x": 480, "y": 348, "w": 6, "h": 14, "score": 0.78},
    #     {"x": 480, "y": 392, "w": 6, "h": 14, "score": 0.81},
    #     {"x": 480, "y": 436, "w": 6, "h": 14, "score": 0.79},
    # ]
    # Sorted top-to-bottom. May be fewer than 3 if some rows are
    # missing / occluded.

The template lives at ``ocr/sc_templates/colon.npz``, generated by
``scripts/build_colon_template.py``.
"""
from __future__ import annotations

import logging
import os
import threading
from typing import Optional

import numpy as np
from PIL import Image

from . import label_match as _lm

log = logging.getLogger(__name__)

# Template location.
_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_TOOL_DIR = os.path.normpath(os.path.join(_THIS_DIR, "..", ".."))
_TEMPLATES_PATH = os.path.join(
    _TOOL_DIR, "ocr", "sc_templates", "colon.npz",
)

# Pre-built scale variants of the colon template. Each entry is
# (canonicalized_float32_template, width, height) where the template
# is already zero-mean unit-variance for direct use with NCC.
_TEMPLATE_CACHE: Optional[list[tuple[np.ndarray, int, int]]] = None
_TEMPLATE_NATIVE_HEIGHT: int = 28

# Minimum NCC score for a confident colon detection. The colon is a
# small glyph so it's relatively sensitive to AA and chromatic noise;
# 0.55 was chosen to admit recoverable matches without false-firing on
# text gaps that contain incidental two-dot patterns (e.g. accents,
# ellipses).
_MIN_COLON_SCORE = 0.55

# Multi-scale sweep. HUD scale varies across captures (different SC
# render sizes, different upstream upscaling). Same scale set as the
# label_match anchors so colon detection covers the same range.
_SCALE_FACTORS = (0.8, 1.0, 1.25, 1.5, 1.75, 2.0)

# NMS Y-distance: detections closer than this are merged into the
# highest-score winner. Sized to the typical colon glyph height
# (~14 px native + multi-scale variants).
_NMS_Y_DISTANCE = 12

# Per-image dedup: a single-entry cache keyed on (id(img), size, mode,
# y_band, x_range) so repeated calls from the same caller within one
# scan don't re-run the multi-scale sweep.
_LAST_CALL_CACHE: Optional[tuple[tuple, list[dict]]] = None
_cache_lock = threading.Lock()


def _load_template() -> Optional[list[tuple[np.ndarray, int, int]]]:
    """Lazy-load the colon template and pre-build scale variants.

    Returns a list of (canonical_template, w, h) at every scale in
    ``_SCALE_FACTORS``, or None if the npz is missing / degenerate.
    Cached after first load.
    """
    global _TEMPLATE_CACHE, _TEMPLATE_NATIVE_HEIGHT
    if _TEMPLATE_CACHE is not None:
        return _TEMPLATE_CACHE
    if not os.path.isfile(_TEMPLATES_PATH):
        log.warning(
            "colon_anchor: template not found at %s — run "
            "scripts/build_colon_template.py to bootstrap it",
            _TEMPLATES_PATH,
        )
        return None
    try:
        data = np.load(_TEMPLATES_PATH)
        if "colon" not in data:
            log.warning(
                "colon_anchor: 'colon' key missing in %s", _TEMPLATES_PATH,
            )
            return None
        raw = data["colon"].astype(np.float32)
        if "height" in data:
            _TEMPLATE_NATIVE_HEIGHT = int(data["height"])
        mean = float(raw.mean())
        std = float(raw.std())
        if std < 1e-3:
            log.warning("colon_anchor: template degenerate (std≈0)")
            return None
        native = (raw - mean) / std
        variants: list[tuple[np.ndarray, int, int]] = []
        for s in _SCALE_FACTORS:
            try:
                resized = _lm._resize_template(native, s)
                # Need at least 3 px each dim — the colon is tiny and we
                # don't want degenerate kernels.
                if resized.shape[0] >= 6 and resized.shape[1] >= 3:
                    variants.append(
                        (resized, resized.shape[1], resized.shape[0])
                    )
            except Exception:
                continue
        if not variants:
            log.warning("colon_anchor: no usable scale variants built")
            return None
        _TEMPLATE_CACHE = variants
        log.info(
            "colon_anchor: loaded template (native h=%d) -> %d scale "
            "variants from %s",
            _TEMPLATE_NATIVE_HEIGHT, len(variants), _TEMPLATES_PATH,
        )
        return _TEMPLATE_CACHE
    except Exception as exc:
        log.warning("colon_anchor: template load failed: %s", exc)
        return None


def reset_cache() -> None:
    """Force template + per-image cache to rebuild on next call.

    Call after rebuilding ``colon.npz`` so the new template takes
    effect without a process restart.
    """
    global _TEMPLATE_CACHE, _LAST_CALL_CACHE
    with _cache_lock:
        _TEMPLATE_CACHE = None
        _LAST_CALL_CACHE = None


def _nms(detections: list[dict], y_distance: int) -> list[dict]:
    """Greedy non-maximum suppression on Y axis.

    Keeps the highest-score detection in each Y window of width
    ``y_distance``. Detections are sorted by Y after NMS.
    """
    if not detections:
        return []
    # Sort by score descending, then walk and keep what doesn't conflict.
    ordered = sorted(detections, key=lambda d: -d["score"])
    kept: list[dict] = []
    for d in ordered:
        y_center = d["y"] + d["h"] // 2
        ok = True
        for k in kept:
            k_center = k["y"] + k["h"] // 2
            if abs(y_center - k_center) < y_distance:
                ok = False
                break
        if ok:
            kept.append(d)
    kept.sort(key=lambda d: d["y"])
    return kept


def find_colons(
    img: Image.Image,
    y_band: tuple[int, int],
    x_range: Optional[tuple[int, int]] = None,
) -> list[dict]:
    """Find all colon glyphs within ``y_band`` (and optional ``x_range``).

    Multi-scale NCC sweep against the canonical colon template, with
    Y-axis NMS to collapse near-duplicate detections at adjacent scales.

    Args:
        img: Source panel image (RGB or grayscale PIL).
        y_band: ``(top, bottom)`` in image coordinates, inclusive of
            ``top``, exclusive of ``bottom``. Search is restricted to
            this strip for efficiency.
        x_range: Optional ``(left, right)`` in image coordinates. When
            None, scans the full image width. Restricting the X range
            past the leftward label start helps reject incidental
            two-dot patterns inside icon glyphs or panel chrome.

    Returns:
        List of detection dicts ``{"x", "y", "w", "h", "score"}`` in
        image coordinates, sorted top-to-bottom. Empty list when no
        detections cross ``_MIN_COLON_SCORE``.
    """
    global _LAST_CALL_CACHE

    y_top, y_bot = int(y_band[0]), int(y_band[1])
    if x_range is not None:
        x_left, x_right = int(x_range[0]), int(x_range[1])
    else:
        x_left, x_right = 0, img.size[0]
    cache_key = (
        id(img), img.size, img.mode,
        y_top, y_bot, x_left, x_right,
    )
    with _cache_lock:
        if _LAST_CALL_CACHE is not None and _LAST_CALL_CACHE[0] == cache_key:
            return list(_LAST_CALL_CACHE[1])

    variants = _load_template()
    if not variants:
        with _cache_lock:
            _LAST_CALL_CACHE = (cache_key, [])
        return []

    W_img, H_img = img.size
    # Clamp the search region to the image bounds.
    y_top = max(0, min(H_img, y_top))
    y_bot = max(y_top, min(H_img, y_bot))
    x_left = max(0, min(W_img, x_left))
    x_right = max(x_left, min(W_img, x_right))
    if (y_bot - y_top) < 6 or (x_right - x_left) < 6:
        log.debug(
            "colon_anchor: search region too small "
            "(y=[%d,%d] x=[%d,%d])", y_top, y_bot, x_left, x_right,
        )
        with _cache_lock:
            _LAST_CALL_CACHE = (cache_key, [])
        return []

    crop = img.crop((x_left, y_top, x_right, y_bot)).convert("RGB")
    rgb = np.array(crop, dtype=np.uint8)
    # Max-of-RGB-channels rather than luma — same rationale as
    # scan_results_match (preserves chromatic-aberrated stroke shapes
    # against AA blur in the SC HUD font).
    detect = rgb.max(axis=2).astype(np.uint8)
    # For the colon (tiny template), we need PROPER per-window NCC
    # rather than the global-mean cross-correlation that label_match's
    # ``_ncc_search`` uses. The label templates fill most of the
    # window so the global normalization is acceptable; the colon
    # occupies only ~5% of each search window, so without per-window
    # normalization a high-contrast incidental two-dot pattern (e.g.
    # an ellipsis in COMPOSITION text) scores higher than the colon
    # itself. Use a separate, locally-normalized correlator.
    target_f = detect.astype(np.float32)

    detections: list[dict] = []
    try:
        from scipy.signal import fftconvolve  # type: ignore
    except Exception as exc:
        log.debug("colon_anchor: scipy unavailable: %s", exc)
        with _cache_lock:
            _LAST_CALL_CACHE = (cache_key, [])
        return []
    for tmpl_norm, tw, th in variants:
        if tw > target_f.shape[1] or th > target_f.shape[0]:
            continue
        # tmpl_norm is already zero-mean unit-variance over the WHOLE
        # template (built in _load_template). For proper sliding-window
        # NCC we need: NCC(x,y) = sum((target_patch - patch_mean) *
        # (tmpl - tmpl_mean)) / (patch_std * tmpl_std * n)
        # Since tmpl_norm has tmpl_mean=0 and L2-norm ≈ sqrt(n) (unit
        # variance) we can simplify to:
        # NCC(x,y) = cross(target, tmpl_norm) / (patch_std * sqrt(n))
        # where patch_std is the local std of target over each window.
        h, w = tmpl_norm.shape
        n = float(h * w)
        # 1) Cross-correlation: fftconvolve(target, tmpl[::-1,::-1])
        try:
            cross = fftconvolve(
                target_f, tmpl_norm[::-1, ::-1], mode="valid",
            )
        except Exception:
            continue
        if cross.size == 0:
            continue
        # 2) Per-window sum + sum-of-squares for local std.
        ones = np.ones_like(tmpl_norm)
        try:
            patch_sum = fftconvolve(target_f, ones[::-1, ::-1], mode="valid")
            patch_sq_sum = fftconvolve(
                target_f * target_f, ones[::-1, ::-1], mode="valid",
            )
        except Exception:
            continue
        patch_mean = patch_sum / n
        patch_var = patch_sq_sum / n - patch_mean * patch_mean
        patch_var = np.clip(patch_var, 1e-6, None)
        patch_std = np.sqrt(patch_var)
        # NCC: cross / (n * patch_std). Since tmpl_norm has unit variance,
        # its L2 squared is n, so L2 is sqrt(n). And the cross is sum of
        # (window_pixel * tmpl_norm_pixel). Dividing by n * patch_std
        # gives correlation in [-1, 1].
        with np.errstate(invalid="ignore", divide="ignore"):
            ncc = cross / (n * np.where(patch_std > 1e-6, patch_std, 1.0))
        # Mask out near-zero-variance windows (uniform regions can't
        # match anything meaningfully).
        ncc = np.where(patch_std > 1e-3, ncc, -1.0)
        if ncc.size == 0:
            continue
        # Pick local maxima above threshold. For colon detection we
        # want MULTIPLE per scale (one per row), so we scan each row
        # for the best column and accept rows above threshold.
        # Rows whose best score crosses the threshold:
        row_max = ncc.max(axis=1)
        for y_rel in range(ncc.shape[0]):
            score = float(row_max[y_rel])
            if score < _MIN_COLON_SCORE:
                continue
            x_rel = int(np.argmax(ncc[y_rel]))
            detections.append({
                "x": int(x_left + x_rel),
                "y": int(y_top + y_rel),
                "w": int(tw),
                "h": int(th),
                "score": float(score),
            })

    # Y-axis NMS: collapse multi-scale duplicates of the same true colon.
    kept = _nms(detections, _NMS_Y_DISTANCE)

    log.debug(
        "colon_anchor: found %d colons (from %d raw, y_band=[%d,%d] "
        "x_range=[%d,%d])",
        len(kept), len(detections), y_top, y_bot, x_left, x_right,
    )
    with _cache_lock:
        _LAST_CALL_CACHE = (cache_key, list(kept))
    return kept
